logging:
  level:
    root: WARN
    com.irrigation_system.iot: INFO
    com.irrigation_system.iot.schedule: INFO
    com.irrigation_system.iot.service: INFO
    org.hibernate: WARN
    org.springframework: WARN
    org.springframework.boot: WARN
    org.springframework.scheduling: INFO
    com.zaxxer.hikari: WARN

management:
  endpoint:
    health:
      show-details: when-authorized
  endpoints:
    web:
      exposure:
        include: health,metrics
