spring:
  profiles:
    active: ${ENVIRONMENT_CONFIG:dev}
  application:
    name: irrigation-system
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  main:
    allow-bean-definition-overriding: true
  mvc:
    async:
      request-timeout: -1 # no timeout for StreamingResponseBody (CSV export)
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/irrigation_system_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true}
    username: ${DATABASE_USERNAME:admin_user}
    password: ${DATABASE_PASSWORD:irrigation_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 200
          time_zone: Asia/Ho_Chi_Minh
    show-sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  cache:
    type: caffeine
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:rabbitmq_user}
    password: ${RABBITMQ_PASSWORD:rabbitmq_password}
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 200
        batch-size: 200
        consumer-batch-enabled: true
  mail:
    host: ${HOST_SMTP:smtp.gmail.com}
    port: ${PORT_SMTP:587}
    username: ${USERNAME_SMTP:mentorbookingnotification@gmail.com}
    password: ${PASSWORD_SMTP:idejizktdncupvmd}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

identity:
  jwt:
    secret-key: ${JWT_SECRET_KEY:cb3f30b0ec715f1bcbead50dc9d77786c038b569f2f6adb9a9e724e07ffd6c17}
    token-exp: PT15M         # 15 minutes
    refresh-token-exp: P7D   # 7 days
mail:
  sender:
    from: ${MAIL_SENDER_FROM:mentorbookingnotification@gmail.com}
logging:
  file:
    path: ${LOG_PATH:logs}

app:
  env: ${APP_ENV:local}
  irrigation:
    schedule-cron: '0 * * * * *'
    flow-rate-ml-per-minute: 100
    min-duration-seconds: 10
    max-duration-minutes: 120
